# action.yml
name: ddosify action
description: Run performance tests using ddosify
author: NaveenKumar Namachivayam - https://qainsights.com

branding:
  color: blue
  icon: feather

inputs:
  args:
    required: true
    description: Optional arguments. For more details https://jmeter.apache.org/usermanual/get-started.html#non_gui

runs:
    using: "composite"
    steps:
      - run: ./script.sh ${{ inputs.args }}
        shell: bash 
