on: [push]
jobs:
  jmeter_job:
    runs-on: ubuntu-latest
    name: ddosify Test Execution
    steps:      
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Run ddosify tests
        uses: ./
        with:
          args: ""
